### PR TITLE
Fixing Interactable Physics Grab

### PR DESCRIPTION
**Pull request by sean-delcastillo**
## Fixed Interactable constrained by a joint with InteractableGrab moving too aggressively towards Interactor position

https://github.com/stumpynub/NXR/assets/25884470/8a9ae889-b623-467f-bbf9-01e22b14e800

In InteractableGrab's PhysicsGrab method the Interactable's linear and angular velocities' magnitudes are being multiplied by 100

https://github.com/stumpynub/NXR/blob/b12e9cfb0b8a0d0ceeab4cc9772d1580c05e7256/addons/nxr/scripts/interactable/components/InteractableGrab.cs#L142-L144

This resulted in the Interactable glitching out since it was trying to move very quickly towards a position it cannot reach. Instead of the flat factor of 100 I suggest we use a factor of 10 and a clamped value depending on the distance between the Interactable's position and the Interactor.

### InteractableGrab
```cs
state.LinearVelocity = dir * Mathf.Clamp(dir.Length(), 1f, 10f) * 10f;
```

This results in the Interactable correctly keeping position with the Interactor under these circumstances without glitching out when the Interactor gets too far away.

https://github.com/stumpynub/NXR/assets/25884470/3540f029-2036-4586-a767-9764ee9802f1

In addition to limiting the velocity of the Interactable we should also look into adding a system to "disconnect" the Interactor when it gets too far from the Interactable. 

## Wrapped Interactable's physics state changes into RigidBody3D's _IntegrateForces method

Godot's documentation for the RigidBody3D class says that the LinearVelocity property should not be set every frame as it is now (https://docs.godotengine.org/en/stable/classes/class_rigidbody3d.html#class-rigidbody3d-property-linear-velocity). Instead regular changes to the body's physics state should be within the class' _IntegrateForces method. This necessitates changes in both the Interactable and the InteractableGrab classes.

### Interactable
```cs
public delegate void IntegrateForcesDelegate(PhysicsDirectBodyState3D state);
public IntegrateForcesDelegate IntegrateForces {set; get;}
```

Adding a delegate to reference the _IntegrateForces signature and a public property to be set by InteractableGrab.  

### Interactable
```cs
public override void _IntegrateForces(PhysicsDirectBodyState3D state)
{
  if (IntegrateForces is not null)
  {
    IntegrateForces(state);
  }
}
```

Wrapping the property callback within the _IntegrateForces method and passing the physics state into it.

### InteractableGrab
```cs
Interactable.IntegrateForces = (PhysicsDirectBodyState3D state) =>
{
  state.LinearVelocity = dir * Mathf.Clamp(dir.Length(), 1f, 10f) * 10f;
  state.AngularVelocity = angularVelocity;
};
```

Setting the property to a function that modifies the physics state as needed.

This implementation sets the property every physics frame. This feels wrong, but it works for now. Might explore different avenues to this later. 

## Added new demo scene to demonstrate new Interactable implementations

Right now only contains the door demo in the videos above. Could be useful to show off future Interactable implementations that do not fit the theme of the Killhouse demo. 

Contains Prototype Textures by Kenney (https://kenney-assets.itch.io/prototype-textures) which are licensed by CC0 1.0 (https://creativecommons.org/publicdomain/zero/1.0/).

--- 

I would appreciate any feedback on this PR, particularly on the implementation of the IntegrateForces property and the inclusion of the new demo scene.

### CODE REVIEW

**Comment by stumpynub** [comment]
Have a missing dependency for XRSimulator in Demo2. When fixed, it worked and felt amazing! I like the idea of having multiple demo scenes so maybe we can open a discussion about managing that! Haven't had a ton of feedback overall about the toolkit so any feedback or big changes you think need to happen, feel free to share! :D     

Also, one of the fixes I had been meaning to push might work nicely with this. Removes some magic numbers, as well. 

```
dir /= (float)GetPhysicsProcessDeltaTime(); 
state.LinearVelocity = dir.LimitLength(_maxGrabbedVelocity);
```
Dividing by delta results in a much more instant and accurate update

**Comment by sean-delcastillo** [comment]
Sounds good! I merged master into the PR to update it with your most recent changes and removed the node causing the dependency. I'm using another addon to simulate XR inputs so I don't have to keep putting my VR headset on/off during development 😆 and I forgot to remove the node before pushing the demo2 scene changes. I can open up a discussion on demo scenes as well to organize further discussion on demo contents!

As for this PR, I noticed these lines in from master that break the current physics implementation for Interactable/InteractableGrab.
https://github.com/stumpynub/NXR/blob/967eeb92f79d828f2c275be0002ddfb6e30336ed/addons/nxr/scripts/interactable/Interactable.cs#L84-L87

If its alright with you, I think its best to revert it to the last implementation so we can close out this PR and move improving it to a later issue. Thanks for the eyes on this PR! 😄

**Comment by stumpynub** [comment]
Oops that was old me trying to solve pretty much the same issue. Changed back to how you had it, and fixed the grab point again. If everything works on your end should be good to merge! Sorry in advance, I'm a tad bit inexperienced in collaboration.

**Comment by sean-delcastillo** [comment]
No worries. I'm glad to be working with you! I just tested it and it works, and that new grab break functionality is working well too. This PR looks good to merge to me 👍.

In the future, you should be able to make commits directly to the feature branch on my fork to edit the PR. It should save you the trouble of managing a mirrored branch over here in the upstream repo and automatically update the PR with your changes.

**Review by stumpynub — APPROVED** [review]

**Pull request merged**
